server:
  port: 8082
  servlet:
    context-path: /api/V1.0

spring:
  application:
    name: customer
  datasource:
    username: bank
    password: password
    url: jdbc:postgresql://localhost:5434/bank
  jpa:
    open-in-view: off
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true

jwt-security:
  secret: secret_word
  expiration: 86400000ms

logging:
  level:
    root: info
